uint8 side

uint8 TOUCH_LINE_LEFT_TOP     = 0
uint8 TOUCH_LINE_LEFT_BOTTOM  = 1
uint8 TOUCH_LINE_LEFT_BOTH    = 2
uint8 TOUCH_LINE_RIGHT_TOP    = 3
uint8 TOUCH_LINE_RIGHT_BOTTOM = 4
uint8 TOUCH_LINE_RIGHT_BOTH   = 5
---
