/* Copyright (C) ZJUDancer
 * 2018 - Yusu Pan <xxdsox@gmail.com>
 * 2017 - Wenxing Mei <mwx36mwx@gmail.com>
 */

/**
 * @file dconstant.hpp
 * @brief
 * @author Yusu Pan, Wenxing Mei
 * @version 2018
 * @date 2018-02-24
 */

#pragma once

namespace dconstant {
namespace geometry {
// Field geometry in cm, refer to RoboCup Humanoid Rules
const int fieldLength = 900;
const int fieldWidth = 600;
const int goalDepth = 60;
const int goalWidth = 260;
const int goalHeight = 180;
const int goalAreaLength = 100;
const int goalAreaWidth = 300;
// const int goalAreaWidth = 500;
const int penaltyAreaLength = 200;
const int penaltyAreaWidth = 500;

const int penaltyMarkDistance = 150;
// const int penaltyMarkDistance = 210;
const int centerCircleDiameter = 150;
const int borderStripWidth = 70;
const int lineWidth = 5;

const int wholeWidth = fieldLength + borderStripWidth * 2;
const int wholeHeight = fieldWidth + borderStripWidth * 2;

const int ballDiameter = 15;
const int robotWidth = 30;
const int robotHeight = 20;

const int field_length_half = fieldLength >> 1;
const int field_width_half = fieldWidth >> 1;
const int goal_area_width_half = goalAreaWidth >> 1;
const int goal_width_half = goalWidth >> 1;
const int center_circle_radius = centerCircleDiameter >> 1;
}  // namespace geometry

namespace network {
const int NUM_ROBOT = 6;
// Generated by https://www.random.org/
const int robotBroadcastAddressBase = 48175;   // should be robotVisionBase
const int robotCannyBase = 10329;
const int robotGuiBase = 7236;
const int robotMotionBase = 13892;

const int monitorBroadcastAddressBase = 26333;   // should be monitorVisionBase
const int TeamInfoBroadcastAddress = 57335;      // should be monitorVisionBase

const int NETWORK_FREQ = 30;
}  // namespace network  // namespace network

}   // namespace dconstant
